.TH "CVS" "5" "Jun 2003" "Portage 2.0.48" "Portage"
.SH "名前"
cvs \- 一般的な cvs fetch 機能を提供
.SH "説明"
\fBcvs\fR eclass は「live」cvs ebuild を作成するために使うことができる
関数を持っている。「live」cvs ebuild という名前は、emerge の時 cvs
リポジトリからチェックアウトし、そのチェックアウトしたソースコードから
コンパイルするために、そう呼ばれている。
この eclass は普通とても不安定な ebuild を生成する……が、
「live」cvs チェックアウト以上の最先端を使うことはできないだろう :)

.br
この eclass のよくある利用方法としては、まず \fBECVS_SERVER\fR 
と \fBECVS_MODULE\fR を設定して適切な cvs ソースを取得し、
cvs eclass で \fBsrc_unpack\fR を定義してもらう。
.SH "変数"
.TP
.B "ECVS_CVS_COMMAND" = \fI"cvs -q -f -z4"\fR
cvs リポジトリからモジュールをチェックアウトするために実行するコマンド。
これを変更する必要はない。
.TP
.B "ECVS_UP_OPTS" = \fI"-dP"
update を実行する時に \fBECVS_CVS_COMMAND\fR に渡すオプション。
これを変更する必要はない。
.TP
.B "ECVS_CO_OPTS" = \fI""\fR
checkout を実行する時に \fBECVS_CVS_COMMAND\fR に渡すオプション。
これを変更する必要はない。
.TP
.B "ECVS_TOP_DIR" = \fI"${DISTDIR}/cvs-src"\fR
cvs モジュールが保存され、そしてアクセスされる場所。
これを変更する必要はない。
.TP
.B "ECVS_SERVER" = \fI"offline"\fR
この変数にはソースを checkout するサーバを設定する。
この変数に「offline」を設定すると、cvs eclass はモジュールが
すでに checkout されていて \fBECVS_TOP_DIR\fR にあると仮定する。
ほぼ必ずこの変数は設定しなければならない。
.TP
.B "ECVS_AUTH" = \fI"pserver"\fR
ソースを checkout するために使う認証方法。
現在サポートされている方法は「pserver」だけであることに注意。
これを変更する必要はない。
.TP
.B "ECVS_USER" = \fI"anonymous"\fR
サーバにログインするユーザ名。
.TP
.B "ECVS_PASS" = \fI""\fR
サーバにログインするパスワード。
.TP
.B "ECVS_MODULE" = \fI""\fR
cvs サーバから checkout するモジュール名。
この変数は *必ず* 設定することに注意。
.TP
.B "ECVS_BRANCH" = \fI"HEAD"\fR
ソースを checkout するブランチ。
よくあるターゲットは HEAD (現在「stable」の cvs コード) と
SPLIT (現在「unstable」の cvs コード)。
.SH "関数"
.TP
.B cvs_fetch
この関数は \fBECVS_TOP_DIR\fR をセットアップし、
その他 checkout の前に必要な準備を実行する。
そしてサーバにログインし、最終的に cvs からソースを checkout する。
普通この関数を自分で呼ぶ必要はなく、
\fBcvs_src_unpack\fR に実行させる。
.TP
.B cvs_src_unpack
この関数は cvs ファイルを保存し、checkout のあと置いておく必要の
ある場所を決める。最終的な結果としては、\fB${WORKDIR}\fR の
\fBECVS_MODULE\fR に cvs ソースコードのコピーが保存される。
したがって、大抵 \fB${S}\fR には \fB${WORKDIR}/${ECVS_MODULE}\fR
を設定することになる。
.SH "バグ報告"
バグ報告は http://bugs.gentoo.org/ 経由で行ってください。
.SH "参照"
.BR ebuild (5)
.SH "ファイル"
.BR /usr/portage/eclass/cvs.eclass
.SH "著者"
Mike Frysinger <vapier@gentoo.org>
.SH "CVS ヘッダ"
原文: /home/cvsroot/gentoo-src/portage/man/cvs.5,v 1.2 2003/07/13 04:25:36 vapier
