.\" Copyright 1999-2004 Gentoo Technologies, Inc.
.\" Distributed under the terms of the GNU General Public License v2
.\"
.\" Original version: 2004-06-18
.\" Translated on 18 Jun 2004 by Mamoru KOMACHI <usata@gentoo.gr.jp>
.\"
.TH "DISPATCH-CONF "1" "May 2004" "Portage 2.0.50" "Portage"
.SH 名前
dispatch-conf \- 新しいパッケージをemergeしたあとに正しく設定をアップデートする
.SH 書式
.B dispatch-conf
.SH 説明
.I dispatch-conf
は新しいパッケージをインストールしたあと、設定ファイルに更新があるかどうか調べるためにに起動するようデザインされている。もし新しい設定ファイルが古い設定ファイルを上書きするようであれば、
.I dispatch-conf 
はユーザに入力を促し食い違いを解決する方法を選択させる。
.I dispatch-conf
の利点は、簡単にロールバック(設定ファイルへの変更は、パッチもしくは rcs の形で保存される)できることと、ユーザーがいじったことのない設定ファイルや、現在の設定ファイルと CVS タグかスペースしか違わない設定ファイルを自動で更新できたりすることである。

.I dispatch-conf
will check all directories in the \fICONFIG_PROTECT\fR variable.  All
config files found in \fICONFIG_PROTECT_MASK\fR will automatically be
updated for you by \fIdispatch-conf\fR.  See \fBmake.conf\fR(5) for more
information.
.SH オプション
.TP
なし。
.SH 使用方法
更新される設定ファイルは大概 root が所有しなければならないため、
.I dispatch-conf
は root で実行される必要がある。初めて
.I dispatch-conf
を実行する前に、
.B /etc/dispatch-conf.conf
にある設定を編集し、
\fI/etc/dispatch-conf.conf\fR で指定されているアーカイブディレクトリを作成しなければならない。設定ファイルへの変更は全部パッチもしくは rcs を用いてアーカイブディレクトリに保存されるので、以前の設定ファイルに書き戻すことも比較的容易である。

dispatch-conf が更新のある設定ファイルを検出したとき、ユーザーはその更新を処理するためのオプションメニューを提示される:
.TP
.B u
現在の設定ファイルを新しい設定ファイルで更新(Update)し、続行。
.TP
.B z
新しい設定ファイルを削除(Zap)し、続行。
.TP
.B n
次(Next)の設定ファイルへとスキップし、元の設定ファイルと
\fICONFIG_PROTECT\fR されたファイルの双方をそのままにする。
.TP
.B e
\fI$EDITOR\fR で設定されたエディターを用いて新しい設定ファイルを編集(Edit)する。
.TP
.B m
現在の設定ファイルと新しい設定ファイルを対話的に統合(Merge)する。
.TP
.B l
統合される前の設定ファイルと、統合されたあとの設定ファイルの違いを見る(Look)。
.TP
.B t
統合された設定ファイルと統合前の設定ファイルをトグル(Toggle)する。
(
.Qt u
コマンドでインストールされる設定ファイルを切り替える).
.TP
.B h
ヘルプ画面を表示する。
.TP
.B q
Quit
.I dispatch-conf.
.SH "バグ報告"
http://bugs.gentoo.org/ 経由でバグ報告してください。
.SH "参照"
.BR make.conf (5), etc-update (1)
.SH "ファイル"
.TP
.B /etc/dispatch-conf.conf
\fIdispatch-conf\fR の設定ファイルがここに保存される。
.SH 作者
Jeremy Wohl
.br
Karl Trygve Kalleberg <karltk@gentoo.org>
.br
Mike Frysinger <vapier@gentoo.org>
.br
Grant Goodyear <g2boojum@gentoo.org>
.SH "CVS ヘッダー"
原文: dispatch-conf.1,v 1.1 2004/05/02 17:58:02 vapier
