.\" Copyright 1999-2004 Gentoo Technologies, Inc.
.\" Distributed under the terms of the GNU General Public License v2
.\"
.\" Origial version: 2.0.50
.\" Translated on 16 Jun 2004 by Mamoru KOMACHI <usata@gentoo.gr.jp>
.\"
.TH "G-CPAN.PL" "1" "Feb 2004" "Portage 2.0.50" "Portage"
.SH 名前
g-cpan.pl \- CPAN 提供の Perl モジュールを Gentoo の Portage でインストール
.SH 書式
\fBg-cpan.pl\fR <\fImodule-name\fR>
.SH "説明"
.B g-cpan.pl
は(依存関係も含めた)CPANモジュールをGentooのPortageを用いてインストールするためのPerlスクリプトである。g-cpan.plは依存情報とインストールされたファイルをあたかも普通のebuildからインストールしたかのように記録する。

初めて\fBg-cpan.pl\fRを起動すると、CPAN環境の設定をするよう訊かれる。
ほとんどのユーザーは尋ねられたデフォルトのまま同意すればよい。
.SH "実行例"
Jabber::RPC をインストールする

# \fBg-cpan.pl Jabber::RPC\fR
.SH "作者"
J Robert Ray <jrray@gentoo.org> (g-cpan.pl)
.br
Sven Vermeulen <swift@gentoo.org> (manページ)
.SH "バグ報告"
バグ報告は http://bugs.gentoo.org/ 経由でしてください。
.SH "CVSヘッダー"
原文: /home/cvsroot/gentoo-src/portage/man/g-cpan.pl.1,v 1.1 2004/02/28 05:32:10 vapier
