.\" Copyright 1999-2004 Gentoo Technologies, Inc.
.\" Distributed under the terms of the GNU General Public License v2
.\"
.\" Original version: 1.1
.\" Translated on 21 Feb 2004 by Akinori Hattori <hattya@gentoo.org>
.\"
.TH pkg-clean "1" "Nov 2003" "gentoolkit"
.SH "名前"
pkg-clean \- Gentoo: 必要のないパッケージを消す
.SH "書式"
.B pkg-clean
.SH "バグ"
このツールにはまだ man ページがない。このことについてのバグは 
http://bugs.gentoo.org に気軽に投稿していただきたい。
.SH "著者"
この情報を提供する man ページは Karl Trygve Kalleberg <karltk@gentoo.org> によっ
て書かれた。

