.\" Copyright 1999-2003 Gentoo Technologies, Inc.
.\" Distributed under the terms of the GNU General Public License v2
.\"
.\" Original version: 1.6
.\" Translated on 16 Oct 2003 by Hattya <hattya@inter7.jp>
.\"
.TH "qpkg" "1" "1.6" "gentoolkit 0.1.11-r1" ""
.SH "名前"
qpkg \- Gentoo Linux パッケージ問い合わせツール
.SH "書式"
.LP 
.B qpkg\fR	[\fIoptions\fR] [\fIpkgname\fR] [\fI\-g group\fR]
.br 
	[\fI\-f <file>\fR|\fI\-fp <pattern>\fR]
.TP 
.B qpkg	\fI\-\-dups\fR	[\fI\-\-slot\fR]
.TP 
.B qpkg	\fI\-\-help\fR
.SH "説明"
qpkg は GenToolKit に含まれるパッケージ問い合わせツールである。これを使用すれば、ファイルシステム上に存在するファイルの持ち主であるパッケージを見つけることができたり、パッケージの整合性を確認できたりする。そしてさらに、インストール済み如何に関わらずパッケージに対する問い合わせを行うことができる。
.SH "オプション"
.LP 
.I Duplicate Locating:
.LP 
.B \-d, \-\-dups\fR		複数のバージョンがインストールされているパッケージ
.br
				を表示する。
.br 
.B \-s, \-\-slot\fR		\-d オプションを同じ SLOT に限定する。
.LP 
.I Package Selection:
.LP 
.B \-f, \-\-find\-file\fR	<file> の持ち主であるパッケージを探す
.br 
.B \-fp, \-\-find\-pattern\fR	*<pattern>* にマッチするファイルの持ち主であるパッ
.br
				ケージを探す
.br 
.B \-I, \-\-installed\fR	インストール済みのパッケージから検索する
.br 
.B \-U, \-\-uninstalled\fR	インストールされていないパッケージから検索する
.br 
.B \-g, \-\-group\fR		グループから検索する (他の検索条件と組み合わせるこ
.br 
				とができる)
.LP .I Information Selection:
.LP 
.B \-l, \-\-list\fR		パッケージに属するファイルのリスト
.br 
.B \-i, \-\-info\fR		パッケージの説明とホームページ URL を表示する
.br 
.B \-ct, \-\-check\-time
.br 
.B \-tc, \-\-time\-check\fR	パッケージに属するファイルのタイムスタンプを検証
.br 
.B \-cm, \-\-check\-md5
.br 
.B \-mc, \-\-md5\-check\fR	パッケージに属するファイルの md5 を検証
.br 
.B \-c, \-\-check\fR		パッケージに属するファイルの修正時刻と md5 を検証
.br 
.B \-q, \-\-query\-deps\fR	選択されたパッケージに依存した、全てのインストー
.br 
\fR				ル済みパッケージを表示する
.br 
.I Operation Modifiers:
.LP 
.B \-nc, \-\-no\-color\fR	カラー表示をしない
.br 
.B \-v, \-\-verbose\fR		さらに詳しく表示する [2段階]
.br 
.B \-vv\fR				\-v \-v と同じ
.SH "注意"
\fI\-f, \-fp, \-d, \-l, \-ct, \-cm, \fRそして \fI\-c\fR はインストール済みパッケージでのみ適用される。
.br 
.TP 
短いオプションを組み合わせて指定することはまだできない。
.TP 
バージョン 1.6 においていくつかのオプションは標準でバージョンナンバーを出力しないようになり、かわりに -v または -vv オプションを使用するように動作が変更された。
.TP
もし、-v オプションを重複して（\fI\-vv\fR と等しい）指定せずに、\fI\-f\fR を \fI\-l\fR もしくは \fI\-\-check.. \-v\fR オプションと組合せて使う場合、一致したファイルのみが表示される。
.TP 
\fI\-q\fR オプションを使用する場合には、qpkg が依存情報を調べる際にバージョンを含めて調べるに至っていない（合理的にそうなっている）ため、名前でしか調べないことに十分注意しなくてはならない。システムにおける依存情報をより確実に調べるためには \fBdepclean\fR か、\fBemerge --dep-clean\fR を使用するべきである。
.SH "例"
.LP 
.B qpkg \fI\-\-dups\fR		重複してインストールされているパッケージを表示する
.br 
.B qpkg \fI\-\-dups \-v\fR..	さらにバージョンを表示する
.br 
.B qpkg\fR				全パッケージのリストを表示する
.br 
.B qpkg\fR porta \fI\-I\fR		インストール済みの Portage を表示する
.br 
.B qpkg porta \fI\-i\fR		.. + Portage ツリーに存在する + 
.br 
				説明とホームページの URL を表示する
.br 
.B qpkg gawk \fI\-c \-v\fR	インストール済み gawk の全バージョンの整合性を確認
.br
				する。古いバージョンのファイルは壊れているだろう。
.br 
.B qpkg \fI\-f\fR /bin/ls	/bin/ls が属しているパッケージを表示する
.SH "著者"
Vitaly Kushneriuk <vitaly@gentoo.org>, 2002: qpkg
.br 
Karl Trygve Kalleberg <karltk@gentoo.org>, 2002: man page
.br 
Brandon Low <lostlogic@gentoo.org>, 2002: maintainance
.SH "関連項目"
ebuild(5) 
.TP 
\fI/usr/bin/qpkg\fR スクリプト
.TP 
