.TH "VIM" "5" "Jun 2003" "Portage 2.0.48" "Portage"
.SH "名前"
vim \- vim-core、vim と gvim のための共通ビルドルーチン
.SH "説明"
\fBvim\fR eclass は \fBvim-core\fR、\fBvim\fR と \fBgvim\fR
をビルドするのに使われる関数セットを持っている。
vim-core ebuild は xxd と vimtutor バイナリに加え、
/usr/share/vim、/usr/share/doc と /etc/vim
にインストールされる共通ファイルである。
vim ebuild は端末ベースのバージョンの vim である。
gvim ebuild はグラフィカルなバージョンの vim である。
これら3つの ebuild は同じソース、同じパッチ、
そしてほとんど同じ configure オプションからからビルドされる。
.P
\fBvim.eclass\fR を使った ebuild の中で定義する関数がないのは、
vim.eclass が展開、コンパイルそしてインストールまで全部やるからである。
.SH "変数"
.TP
.B VIM_VERSION = \fI"バージョン文字列"\fR
この変数は重要である。というのは、その ebuild バージョン
(たとえば 6.2_pre5) が vim のバージョン (たとえば 6.2e)
に相当するのにもかかわらず、ebuild
の作者がこの変数を設定しなければ ebuild は vim のバージョン (6.2e)
を知る方法がないからである。
歴史的には vim.eclass 内で ebuild のバージョンから vim
のバージョンを計算する方法があったのだが、
そうすると ebuild の作者は毎回 ebuild
が正しくバージョンづけられているのか確認しなければならなかった。
この問題を回避するために ebuild 自体の中で \fBVIM_VERSION\fR 
を単に指定することで、バージョンの確認が簡単になった。
.TP
.B VIM_GENTOO_PATCHES = \fI"ファイル名"\fR
vim に当てる Gentoo のパッチのファイル名。 vim の新バージョンに対して
Gentoo のパッチを更新する必要は必ずしもないので、
この変数は ebuild や vim のバージョンと、
パッチ tarball のバージョンを分離する。
パッチディレクトリのレイアウトについては、たとえば
\fBvim-6.2.011-gentoo-patches.tar.bz2\fR
を見るとよい。
.TP
.B VIM_ORG_PATCHES = \fI"ファイル名"\fR
vim に当てるパッチのファイル名。
これは \fBftp://ftp.vim.org/pub/vim/patches/\fR から取得した
パッチの tarball であり、現在のバージョンの vim に当てるものである。
vim.org のパッチ tarball の例としては、
たとえば \fBvim-6.2.011-patches.tar.bz2\fR を参照。
.SH "バグ報告"
バグ報告は http://bugs.gentoo.org/ 経由で行なってください。
.SH "参照"
.BR ebuild (5)
.BR vim (1)
.SH "ファイル"
.BR /usr/portage/eclass/vim.eclass
.SH "著者"
Aron Griffis <agriffis@gentoo.org>
.br
Ryan Phillips <rphillips@gentoo.org>
.br
Seemant Kulleen <seemant@gentoo.org>
.SH "CVS ヘッダ"
原文: /home/cvsroot/gentoo-src/portage/man/vim.5,v 1.1 2003/06/29 22:32:25 agriffis
