.\"
.\" Japanese Version Copyright (c) 2004 Shigehiro IDANI
.\"     all rights reserved
.\" Translated on 21 Oct 2004 by Shigehiro IDANI <datam@anet.ne.jp>
.\"
.TH "EBOOK.ECLASS" "5" "Aug 2004" "Portage 2.0.51" "portage"
.SH "名前"
ebook \- ebooksの簡単な導入機能を提供する
.SH "説明"
\fBebook\fR eclass は、ebook の ebuild を書く作業を簡単なものにする。
.SH "変数"
\fI注意\fR: 次の変数は、\fBebook\fR eclass を継承する \fB前に\fR 設定すること:
.TP
.BR "説明"
パッケージに関する説明。 "\fB${P}\fR ebook based on ebook eclass" が初期値である。
.TP
.BR "RDEPEND"
実行時依存関係。 ">=dev-util/devhelp-0.6" が初期値である。
.TP
.BR "EBOOKNAME"
ebook の名称。この変数は \fI必ず\fR 設定すること。
.TP
.BR "EBOOKVERSION"
ebook のバージョン。たとえバージョンがなかったとしても、この変数は \fI必ず\fR 設定すること。
詳細については 下記の \fB${NOVERSION}\fR 変数を参照する。
.TP
.BR "SRC"
拡張子をのぞいた、ダウンロード用のファイル名を設定する。
この変数の初期値は \fB${EBOOKNAME}\fR-\fB${EBOOKVERSION}\fR である。
.TP
.BR "SRC_URI"
ebook のダウンロード先のURIを設定する。
この初期値は、  "http://lidn.sourceforge.net/books_download/\fB${SRC}\fR.\fB${EBOOKEXT}\fR" となる。
.TP
.BR "EBOOKEXT"
\fB${SRC}\fR のファイル名の拡張子を設定する。
初期値は、 tar.gz である。
.TP
.BR "EBOOKDESTDIR"
\fB${DEVHELPROOT}\fR/books/\fB${EBOOKDIR}\fR 内のこのディレクトリには、
ebookをインストールするディレクトリを設定する。
この変数の初期値として、\fB${EBOOKNAME}\fR-\fB${EBOOKVERSION}\fR が設定される。ただし、
\fB${NOVERSION}\fR 変数が設定されている場合には、\fB${EBOOKNAME}\fR が初期値となる。
.TP
.BR "EBOOKFROMDIR"
この変数には、\fB${SRC_URI}\fR を展開後のebookのHTMLファイルまでのパスを設定する。
このディレクトリは、\fB${WORKDIR}\fR からの相対パスである。
この変数の初期値として、\fB${EBOOKNAME}\fR-\fB${EBOOKVERSION}\fR が設定される。
ただし、\fB${NOVERSION}\fR 変数が設定されている場合には、\fB${EBOOKNAME}\fR が初期値となる。
.TP
.BR "BOOKDEVHELPFILE"
この変数には、ebookのbook.devhelpとしてインストールされるファイル名が設定される。
この変数の初期値として、\fB${EBOOKNAME}\fR-\fB${EBOOKVERSION}\fR.devhelp が設定される。
ただし、\fB${NOVERSION}\fR 変数が設定されている場合は、\fB${EBOOKNAME}\fR.devhelp が初期として設定される。
.TP
.BR "BOOKDESTDIR"
この変数にはebookのHTMLファイルがインストールされるディレクトリ名が設定される。
\fB${EBOOKNAME}\fR-\fB${EBOOKVERSION}\fR が初期となる。ただし、\fB${NOVERSION}\fR が設定されている場合は、\fB${EBOOKNAME}\fR が初期となる。
.TP
.BR "NOVERSION"
この変数が設定されていれば、全ての変数より \fB${EBOOKVERSION}\fR の例が
削除される。
.TP
.BR "DEVHELPROOT"
この変数は、devhelpのデータディレクトリのパスが設定される。
初期値は、 usr/share/devhelp である。
.SH "関数"
\fI注意\fR: 次の関数は、初期値として使われているので、
ebuildから削除するべきである。
.TP
.BR "ebook_src_install"
\fB${BOOKDEVHELPFILE}\fR と全てのHTMLファイルを
\fB${DEVHELPROOT}\fR/books/\fB${EBOOKDESTDIR}\fR へインストールする。
.SH "バグ報告"
バグ報告は http://bugs.gentoo.org/ 経由で行なってください。
.SH "参照"
.BR ebuild (5)
.SH "ファイル"
.BR /usr/portage/eclass/ebook.eclass
.SH "著者"
Aaron Walker <ka0ttic@gentoo.org>
.SH "CVS ヘッダ"
原文: ebook.eclass.5,v 1.2
