.\" Copyright 1999-2004 Gentoo Foundation
.\" Distributed under the terms of the GNU General Public License v2
.\"
.\" Origninal version: 1.2
.\" Translated on 21 Oct 2004 by Shigehiro IDANI <datam@anet.ne.jp>
.\"
.TH "FONT.ECLASS" "5" "Aug 2004" "Portage 2.0.51" "portage"
.SH "名前"
font \- 容易かつ均一にフォントをインストールする
.SH "説明"
\fBfont\fR eclass はできるだけ容易にフォントをインストールしようと試みる。
たいていフォントをインストールするのに必要な全てのこと(スケーラブルフォントのインデックスの作成やフォントキャッシュの更新など)を \fBfont\fR eclass によって透過的に扱うことを可能とする。
.SH "例"
以下に簡単なebuildの例を示す:
.nf
inherit font

DESCRIPTION="a collection of fonts for Nepali users"
HOMEPAGE="http://www.mpp.org.np/"
SRC_URI="mirror://gentoo/${P}.tar.bz2"

LICENSE="freedist"
SLOT="0"
KEYWORDS="alpha amd64 ppc x86"
IUSE=""

DEPEND=""

S="${WORKDIR}/${PN}"
FONT_S=${S}
FONT_SUFFIX="ttf"
.fi
.SH "変数"
.TP
.B "FONT_SUFFIX"
インストールするフォントの添え字を、空白区切りのリストで指定する。
.TP
.B "FONT_S"
フォントをインストールするディレクトリを指定する。
もし指定していない場合は、\fB${S}\fR を代用する。
.TP
.B "DOCS"
インストールするドキュメントを空白区切りのリストで指定する。
.SH "関数"
.TP
.B "font_xfont_config"
X用のフォントファイル用にフォントのインデックスを作成し、
また、もしfonts.aliasファイルが存在すれば、それもインストールする。
この関数は、 \fIfont_src_install\fR から呼びだされる。
.TP
.B "font_xft_config"
fontconfigキャッシュを作成する。
この関数も \fIfont_src_install\fR より呼びだされる。
.TP
.B "font_src_install"
\fB${FONT_SUFFIX}\fR で指定された添え字リストにある添え字で終了する全てのフォントをインストールする。同様に \fB${DOCS}\fR に指定されたドキュメントもインストールする。ebuild が \fIsrc_install\fR 関数を省略している場合、標準の関数として実行される。
.SH "バグ報告"
バグ報告は http://bugs.gentoo.org/ 経由で行ってください。
.SH "参照"
.BR ebuild (5)
.SH "ファイル"
.BR /usr/portage/eclass/font.eclass
.SH "著者"
.nf
Aaron Walker <ka0ttic@gentoo.org>
Mike Frysinger <vapier@gentoo.org>
.fi
.SH "CVS ヘッダ"
原文: font.eclass.5,v 1.2
