.\"
.\" Japanese Version Copyright (c) 2004 Shigehiro IDANI
.\"     all rights reserved
.\" Translated on 21 Oct 2004 by Shigehiro IDANI <datam@anet.ne.jp>
.\"
.TH "HORDE.ECLASS" "5" "Aug 2004" "Portage 2.0.51" "portage"
.SH "名前"
horde \- hordeパッケージの統一的な導入方法
.SH "説明"
\fBhorde\fR eclass は、horde ebuilds を書くのを簡単にする。
\fBhorde\fR eclass は、(\fB${PN}\fR に "-cvs" が含まれる場合に)自動的に \fBcvs.eclass\fR(5) を経由してCVS ebuildに対する操作もサポートする。
.SH "変数"
.BR "HORDE_PHP_FEATURES"
この変数は、mod_phpのUSEフラグの空白区切りリストが設定される。
もし設定されている場合、 \fIhorde_pkg_setup\fR はmod_phpが特定のUSEフラグで
コンパイルされているかを確認する。もしmod_php がHORDE_PHP_FEATURESで指定した
USEフラグでコンパイルされていないならば、ビルドは失敗し、
ユーザに mod_php を指定したUSEフラグで再ビルドする必要があることを報告する。
.SH "関数"
.TP
.BR "horde_pkg_setup"
この関数を実行すると、
操作しづらい \fBwebapp.eclass\fR(5) の内容を操作し、
そして \fIHORDE_PHP_FEATURES\fR のチェックを行う。
.TP
.BR "horde_src_unpack"
直接 CVS ebuildを操作する場合に、この関数は、\fBcvs\fR eclass から \fIcvs_src_unpack\fR を呼びだす。
もし \fIcvs_src_unpack\fR が無ければ、代わりに \fIunpack\fR を呼びだす。
.TP
.BR "horde_src_install"
この関数は、 \fB${S}\fR にある全てのファイルを \fBwebapp\fR eclassの \fB${MY_HTDOCSDIR}\fR ディレクトリにインストールする。この関数は、ドキュメント(READMEと \fB${S}/docs/\fR 以下の全てのファイル)のインストールも行う。
そして、取り扱いが難しい \fBwebapp.eclass\fR(5) の他の内容は処理される。
.TP
.BR "horde_pkg_postinst"
さまざまな情報や警告メッセージを表示するようにする。
.SH "バグ報告"
バグ報告は http://bugs.gentoo.org/ 経由で行ってください。
.SH "参照"
.BR ebuild (5),
.BR cvs.eclass (5),
.BR webapp.eclass (5)
.SH "ファイル"
.nf
.BR /usr/portage/eclass/horde.eclass
.BR /usr/portage/eclass/webapp.eclass
.BR /usr/portage/eclass/cvs.eclass
.fi
.SH "著者"
.nf
Aaron Walker <ka0ttic@gentoo.org>
Mike Frysinger <vapier@gentoo.org>
.fi
.SH "CVS ヘッダ"
原文: horde.eclass.5,v 1.3
