.\"
.\" Japanese Version Copyright (c) 2003 Akinori Hattori
.\"     all rights reserved.
.\" Translated on 17 Oct 2003 by Akinori Hattori <hattya@gentoo.org>
.\"
.TH "DEP-CLEAN" "1" "Copyright 2002 Gentoo Technologies, Inc." "2002-07-18" "GenToolKit's Dependency Checker!"
.SH "名前"
dep-clean \- 必要がないか、依存関係が失われているパッケージを表示
.SH "書式"
dep-clean [\fI-RUNICv\fP]
.SH "説明"
dep-clean はインストール済みのパッケージのうち、必要がないか、依存関係を満たすために必要か、もしくは無関係なものを表示する。無関係なパッケージとは Portage ツリー(/usr/portage)に存在しないもののことをいう。このスクリプトは「一切」システムに変更を与えることは無い。
.SH "オプション"
.TP 4
.B \-N, \-\-needed
必要なパッケージだがインストールされていないものを表示する。(赤)
.TP
.B \-R, \-\-removed
インストールされてはいるが Portage には存在しないパッケージを表示する。(黄)
.TP
.B \-U, \-\-unneeded
インストールされてはいるが必要のないパッケージを表示する。(緑)
.TP
.B \-I, \-\-interactive
処理を始める前に対話的に world ファイルを修正する。
.TP
.B \-C, \-\-nocolor
カラー表示をしない。パッケージの種類は R、U、N により区別される。
.TP
.B \-v, \-\-verbose
さらに詳しく表示する。
.TP
.B \-q, \-\-quiet
最低限の表示しかしない。(パッケージ名のみ)
.SH "注意"
.IP "" 4
このスクリプトを最新に保たれていないシステムや、今まで掃除を('emerge \-c' によって)してこなかったシステム上で実行したとしたら、その出力は当てにはならないだろう。
.IP
同じパッケージの名前が全てのカテゴリーに現れた場合は、間違いなくそのパッケージを更新し、'emerge \-c' を実行する時である。
.IP
\-U、\-N、\-R オプションは組み合わせて指定することができる。標準では \-UNR が指定されたものとして動作する。
.SH "著者"
Jerry Haltom <ssrit@larvalstage.net> (dep-clean)
.br
Brandon Low <lostlogic@gentoo.org> (dep-clean)
.PP
Paul Belt <gaarde@users.sourceforge.net> (man page)
