.\"
.\" Japanese Version Copyright (c) 2004 Akinori Hattori
.\"     all rights reserved.
.\" Translated on 22 Sep 2004 by Akinori Hattori <hattya@gentoo.org>
.\"
.TH equery "1" "Jan 2004" "gentoolkit"
.SH 名前
equery \- Gentoo: パッケージ問い合わせツール
.SH 書式
.B equery
.SH バグ
このつーるにはまだ man ページがない。このことについてのバグは
http://bugs.gentoo.org に気軽に投稿していただきたい。
.SH 著者
この情報を提供する man ページは Karl Trygve Kalleberg <karltk@gentoo.org> によっ
て書かれた。
