.\"
.\" Japanese Version Copyright (c) 2004,2006 Akinori Hattori
.\"     all rights reserved.
.\" Translated on 19 Dec 2004 by Akinori Hattori <hattya@gentoo.org>
.\"
.TH "equery" "1" "Oct 2005" "gentoolkit" ""
.SH 名前
equery \- Gentoo: パッケージ検索ツール
.SH 書式
.B equery  
.I [global\-opts] command [local\-opts]
.PP 

.SH 説明
equery は、パッケージに含まれるファイルの一覧や、USE フラグ、指定されたパッケー
ジに含まれるファイルの md5sum の一覧など、パッケージに関するさまざまな情報を表示
できる柔軟なユーティリティである。

.SH オプション
equery に対して 'command' が必ず必要なオプションである。多くのコマンドは 
\'pkgspec' を必要とし、それは <カテゴリ/>パッケージ名<-バージョン> のような形式
である。つまり、パッケージ名が必須で、カテゴリ名やバージョンは任意ということであ
る。

[global\-opts] は次のうちのどれか:

.B \-q, \-\-quiet   
最小限の表示だけにする
.PP 
.B \-C, \-\-nocolor 
カラー表示をしない
.PP 
.B \-h, \-\-help
ヘルプを表示する
.PP 
.B \-V, \-\-version
equery のバージョンを表示する
.PP 
.B \-N, \-\-no\-pipe
パイプ判定を無効にする
.PP 

ひとつのコマンドのみが実際に実行される。有効なコマンドは次の通り:
.TP 
.B belongs <local\-opts> file
このコマンドは指定されたファイルが含まれている全てのパッケージを表示する。
.br 
注意: 通常、ひとつのファイルは、ひとつのパッケージにのみ含まれている。もし、同一
のファイルが複数のパッケージに含まれている場合、大抵は問題を起こすことになるので
報告 (http://bugs.gentoo.org) すべきである。
.br 
.IP 
<local\-opts> は次のうちのどれか、または全てを指定できる:
.br 
.B \-c, \-\-category cat 
指定された cat カテゴリのみを検索する
.br 
.B \-f, \-\-full\-regex
指定された問い合わせを正規表現として行う
.br 
.B \-e, \-\-earlyout 
見つかった時点で終了する

.PP 
.TP
.B check pkgspec
このコマンドは指定されたパッケージのファイルを、記録されている MD5 サム、タイム
スタンプと比較する。
.PP 
.TP 
.B depends <local\-opts> pkgspec
このコマンドは指定された pkgspec に一致する全ての依存関係を表示する
.br 
<local\-opts> の次のうちのどれか、または全てを指定できる:
.br 
.B \-a, \-\-all\-packages
全ての利用可能なパッケージを検索する (遅い)
.br 
.B \-d, \-\-direct
直接の依存関係のみを検索する (標準)
.br 
.B \-D, \-\-indirect
間接的な依存関係も検索する (とても遅い)
.PP 
.TP 
.B depgraph <local\-opts> pkgspec
このコマンドは pkgspec の依存関係ツリーを表示する。デフォルトでは、お互いがどん
な依存関係であるかを示すためインデントを付けてある。
.br 
.IP 
<local\-opts> は次のうちのどれか、または全てを指定できる:
.br 
.B \-U, \-\-no\-useflags 
USE フラグを表示しない
.br 
.B \-l, \-\-linear    
飾りづけをしない
.PP 
.TP 
.B files <local\-opts> pkgspec
対象パッケージに含まれているファイルの一覧を <local\-opts> で指定される情報とと
もに表示する。
.br 

<local\-opts> は次のものの組み合わせ:
.br 
.B \-\-timestamp
各ファイルのタイムスタンプを表示する。
.br 
.B \-\-md5sum
各ファイルの md5sum を表示する。
.br 
.B \-\-type
各ファイルの種類を表示する
.br 
.B \-\-filter=<rules>
ファイルの種類かパスを元に出力を制限する
.br 
.B \t<rules>
はカンマ区切りのフィルタリングルールのリスト。利用可能なルールは以下の通り:
.br 
.B \t\tdir\ 
ディレクトリ
.br 
.B \t\tobj\ 
ファイル
.br 
.B \t\tsym\ 
シンボリックリンク
.br 
.B \t\tdev\ 
デバイスノード
.br 
.B \t\tfifo
名前付きパイプ
.br 
.B \t\tpath
ファイルのインストール先の最短パス
.br 
.B \t\tconf
設定ファイル ($CONFIG_PROTECT を元に)
.br 
.B \t\tcmd\ 
ユーザコマンド ($PATH を元に)
.br 
.B \t\tdoc\ 
ドキュメント (/usr/share/doc から)
.br 
.B \t\tman\ 
マニュアル (/usr/share/man から)
.br 
.B \t\tinfo
info ページ (/usr/share/info から)
.PP 
.TP 
.B hasuse <local\-opts> useflag
このコマンドは指定された USE フラグの組み合わせに一致するものを、インストール済
みパッケージ、未インストールパッケージ、Portage ツリー、そして Portage オーバー
レイツリーから列挙する。

<local\-opts> \-I のみの指定はできず、\-I は \-p と \-o、もしくは \-p か \-o を
一緒に指定しなければならない。標準では、インストール済みパッケージのみ検索される。
\-o はオーバーレイツリーのみ (インストール済みパッケージを含む) 検索され、
Portage ツリーは検索\fIされない\fR。

.B \-i, \-\-installed
インストール済みパッケージを検索する (標準)
.br 
.B \-I, \-\-exclude\-installed
インストール済みパッケージを検索しない
.br 
.B \-p, \-\-portage\-tree
Portage ツリー (/usr/portage) も検索する
.br 
.B \-o, \-\-overlay\-tree
オーバーレイツリー (/usr/local/portage) も検索する
.PP 
.TP 
.B list <local\-opts> pkgspec
このコマンドは、指定された pkgspec に一致するパッケージを、インストール済みパッケージ、未インストールパッケージ、Portage ツリー、そして Portage オーバーレイツリーから列挙する。標準では、部分一致で検索をする。

<local\-opts> \-I のみの指定はできず、\-I は \-p と \-o、もしくは \-p か \-o を
一緒に指定しなければならない。標準では、インストール済みパッケージのみ検索される。
\-o はオーバーレイツリーのみ (インストール済みパッケージを含む) を検索され、
Portage ツリーは検索\fIされない\fR。

.B \-i, \-\-installed
インストール済みパッケージを検索する (標準)
.br 
.B \-I, \-\-exclude\-installed
インストール済みパッケージを検索しない
.br 
.B \-p, \-\-portage\-tree
Portage ツリー (/usr/portage) も検索する
.br 
.B \-o, \-\-overlay\-tree
オーバーレイツリー (/usr/local/portage) も検索する
.br 
.B \-f, \-\-full\-regex
指定された問い合わせを正規表現として行う
.br 
.B \-e, \-\-exact\-name
完全一致したパッケージのみを列挙する
.br 
.B \-d, \-\-duplicates
複数存在するパッケージのみを列挙する
.br 

\fB例:\fR

equery list zilla \- 'zilla' という文字列を含むパッケージの、インストール済みの全バージョンを列挙する

equery list \-\-exact\-name x11\-libs/gtk+  \- x11\-libs/gtk+ のインストール済みの全バージョンを列挙する

equery list \-\-full\-regex '(mozilla\-firefox|mozilla\-thunderbird)' \- mozilla\-firefox と mozilla\-thunderbird のインストール済みの全バージョンを列挙する

equery list \-\-duplicates \- インストール済みのスロット化されたパッケージを全て列挙する
.PP 
.TP
.B size <local\-opts> pkgspec
このコマンドは指定されたパッケージに含まれるファイルの数と、そのサイズを適切な単
位で出力する。

唯一 <local\-opts> に指定可能な引数:
.br 
.B \-b, \-\-bytes 
バイト単位でサイズを表示する
.PP 
.TP 
.B uses <local\-opts> pkgspec 
pkgspec の USE フラグを表示する。

唯一 <local\-opts> に指定可能な引数:
.br 
.B \-a, \-\-all
未インストールパッケージを含める
.PP 
.TP
.B which pkgspec 
パッケージ pkgspec の ebuild へのフルパスを表示する
.PP 

.SH 未実装オプション
.PP 
.B changes
.PP 
.B glsa \fR \- 当分の間 glsa\-check を使用していただきたい。
.PP 
.B stats



.SH バグ
多くのオプションが実装されていない。コマンドライン解析はいくつかの作業に使えた。
.br 
バグ報告は http://bugs.gentoo.org まで。
.SH 著者
equery, original man page: Karl Trygve Kalleberg <karltk@gentoo.org>, 2003.
.br 
Massive man page updates: Katerina Barone\-Adesi <katerinab@gmail.com>, 2004.

