.\"
.\" Japanese Version Copyright (c) 2003 Akinori Hattori
.\"     all rights reserved.
.\" Translated on 20 Nov 2003 by Akinori Hattori <hattya@gentoo.org>
.\"
.TH mkebuild "1" "Nov 2003" "gentoolkit"
.SH "名前"
mkebuild \- Gentoo: 対話的に ebuild を作成
.SH "書式"
.B mkebuild
.SH "バグ"
このツールにはまだ man ページがない。このことについてのバグは 
http://bugs.gentoo.org に気軽に投稿していただきたい。
.SH "著者"
この情報を提供する man ページは Karl Trygve Kalleberg <karltk@gentoo.org> によっ
て書かれた。

