.\" Copyright 1999-2004 Gentoo Technologies, Inc.
.\" Distributed under the terms of the GNU General Public License v2
.\"
.\" Original version: 1.1
.\" Translated on 21 Feb 2004 by Akinori Hattori <hattya@gentoo.org>
.\"
.TH pkg-size "1" "Nov 2003" "gentoolkit"
.SH "名前"
pkg-size \- Gentoo: パッケージサイズ計算機
.SH "書式"
.B pkg-size 
\fIpackage\fR
.SH "説明"
\fIpackage\fR のサイズを計算する。
.SH "著者"
\fBpkg-size\fR は Karl Trygve Kalleberg <karltk@gentoo.org> によって書かれた。

