.\"
.\" Japanese Version Copyright (c) 2004 Shigehiro IDANI
.\"     all rights reserved
.\" Translated on 21 Oct 2004 by Shigehiro IDANI <datam@anet.ne.jp>
.\"
.TH "FIXHEADTAILS.ECLASS" "5" "Aug 2004" "Portage 2.0.51" "portage"
.SH "名前"
fixheadtails \- 古い形式の head/tail 呼び出しを新しい POSIX 準拠の呼び出し方法に置き換える機能を提供する。
.SH "説明"
\fBfixheadtails\fR eclass は、ファイルを解析して、古い形式の head/tail 呼び出し方法:
.TP
head -# <file>
.TP
を新しい POSIX 準拠の呼び出し方法:
.TP
head -n# <file>
.TP
に置き換える機能を提供する。
.SH "関数"
\fB注意\fR: これらの関数はたいてい \fIsrc_unpack\fR 関数で使われている。
.TP
.BR "ht_fix_file " "\fI<file1> [file2] [file3] [...]\fR"
特定のファイルの head/tail 形式の呼び出し方法を修正する。
.TP
.BR "ht_fix_all"
(再帰的に) 現在のディレクトリを検索し、古い head/tail 形式の呼び出し方法を含むファイルにたいして、それぞれ \fBht_fix_file\fR を呼び出す。
.SH "バグ報告"
バグ報告は http://bugs.gentoo.org/ 経由で行ってください。
.SH "関連項目"
.BR ebuild (5)
.SH "ファイル"
.BR /usr/portage/eclass/fixheadtails.eclass
.SH "著者"
Aaron Walker <ka0ttic@gentoo.org>
.SH "CVS ヘッダ"
$Header: /var/cvsroot/gentoo-src/portage/man/fixheadtails.eclass.5,v 1.3 2004/09/17 00:17:10 vapier Exp $
