.\"
.\" Japanese Version Copyright (c) 2004 Mamoru KOMACHI
.\"     all rights reserved
.\" Translated on 12 Jan 2004 by Mamoru KOMACHI <usata@gentoo.org>
.\"
.TH "esearch" "1" "Januar 11, 2004" "esearch"

.SH "名前"
esearch \- 検索インデックスで 'emerge search' を置換

.SH "書式"
.B esearch
[ オプション ] <パターン>

.SH "説明"
esearch は小さなスクリプトで、まさしく emerge \-s や emerge \-S に
それぞれ似せて動作する。emerge に対する esearch の長所は esearch
が使う検索インデックスである。esearch は emerge \-s/\-S よりはるかに
高速である。

.SH "オプション"
.TP
.B \-\-help, \-h
ヘルプメッセージを表示
.TP
.B \-\-searchdesc, \-S
パッケージの説明も検索
.TP
.B \-\-fullname, \-F
パッケージのフルネーム(カテゴリーを含む)を検索
.TP
.B \-\-compact, \-c
出力形式をもっとコンパクトにする
.TP
.B \-\-ebuild, \-e
見つかったパッケージの ebuild を見る
.TP
.B \-\-output=format, \-o format
ユーザ定義の出力形式を使う
.B format
は特殊文字を含みうる文字列である。
詳しくは「形式」のセクションを参照
.TP
.B \-\-nocolor, \-n
色つき出力に ANSI コードを使わない

.SH "形式"
.TP
.B %c
カテゴリー
.TP
.B %n
パッケージ名
.TP
.B %p
"%c/%n" と同じ
.TP
.B %m
パッケージがマスクされていれば "masked" されていなければ ""
.TP
.B %va
利用可能な最新バージョン
.TP
.B %vi
インストールされている最新バージョン、インストールされていなければ ""
.TP
.B %s
ダウンロードされたファイルのサイズ
.TP
.B %h
ホームページ
.TP
.B %d
説明

.SH "例"
.TP
\f(CWesearch -o "/usr/portage/%p/ChangeLog\\n" ^package$\fP
'package' の ChangeLog への正しいパスを表示する。
.TP
\f(CWesearch -o "%n-%va.ebuild\\n" pattern\fP
現在の ebuild ファイルの名前を表示する。
.TP
\f(CWesearch -o "%p\\n" ^ > package-list\fP
利用可能な全パッケージ一覧を生成する。

.SH "参照"
emerge(1)

.SH "バグ"
まだ既知のバグはない

.SH "作者"
David Peter <davidpeter@web.de>
