.\"
.\" Japanese Version Copyright (c) 2004 Akinori Hattori
.\"     all rights reserved.
.\" Translated on 25 Feb 2004 by Akinori Hattori <hattya@gentoo.org>
.\"
.TH ekeyword "1" "Nov 2003" "gentoolkit"
.SH "名前"
ekeyword \- Gentoo: ebuild キーワードチェンジャー
.SH "書式"
.B ekeyword
.SH "バグ"
このツールにはまだ man ページがない。このことについてのバグは 
http://bugs.gentoo.org に気軽に投稿していただきたい。
.SH "著者"
この情報を提供する man ページは Karl Trygve Kalleberg <karltk@gentoo.org> によっ
て書かれた。
